import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react';
import type { CheckMessage, CheckMeta } from "../lib"
import {HorizontalGridLines, LineSeries, VerticalGridLines, XAxis, XYPlot, YAxis} from 'react-vis';
import axios from 'axios'


const Home: NextPage = () => {
  const [checkList, setCheckList] = useState<Record<string, CheckMessage[]>>({})
  useEffect(() => {
    const evtSource = new EventSource("stream");
    evtSource.onopen = function(e) {
      console.log("open", e)
    }
    evtSource.onmessage = function(e) {
      const data : CheckMessage = JSON.parse(e.data)    
      data.checked_at = new Date(data.checked_at)  
      if (checkList[data.name] == undefined) {
        checkList[data.name] = []
      }
      checkList[data.name] = [...checkList[data.name], data]      
      setCheckList(Object.assign({}, checkList))
    }
    evtSource.onerror = function(err) {
      console.error("err", err);
    };
    return () => {
      evtSource.close()
    }
  }, [])
  
  const [metaMap, setMetaMap] = useState<Record<string, CheckMeta>>({})
  useEffect(() => {
    const tmp = async function () {
      try {
        const res = await axios.get("/meta")
        const data : CheckMeta[] = res.data
        const map : Record<string, CheckMeta> = {}
        data.forEach((d) => {
          map[d.name] = d
        })
        setMetaMap(map)
        console.log(map)
      } catch (e) {
        console.log(e)
      }  
    }
    tmp()    
  }, [])
  const listItems = Object.keys(metaMap).map(k => {
    const m = metaMap[k]
    
    const c = checkList[k]?.sort((a,b) => a.checked_at < b.checked_at ? -1: 1 )
    const data = c?.map((v,i) => {
      const d = new Date(v.checked_at)      
      return {
        x: d.getTime(),
        y: v.duration
      }
    })
    return <div className={styles.card} key={m.name}>
      <h2>{m.name}</h2>
      <p>{m.description}</p>
      <div>
        <XYPlot height={250} width={682}>
          <VerticalGridLines />
          <HorizontalGridLines />
          <YAxis title="ms" />
          <LineSeries data={data} />
        </XYPlot>
      </div>
    </div>
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          STATUSBOARD
        </h1>

        <div className={styles.grid}>
          {listItems}
        </div>
      </main>
    </div>
  )
}

export default Home
